### ISSUE TITLE
Outdated Tested/Supported Versions on Spigot Page

### ISSUE THREAD

**Issue by TheDublord** [AvarionMC/graves#17]
[Spigot Page](https://www.spigotmc.org/resources/graves.116202/)

1.17 and under support was stripped as a part of this [commit](https://github.com/AvarionMC/graves/commit/7675b336d3baa8cde4b886e5666867d84b8871d3). The tested minecraft versions and list of supported versions in the descriptions should be updated to reflect the change.

**Comment by svaningelgem** [comment]
Thanks for noticing it! I've updated the spigot page.

Sadly I can't make it easily searchable that "4.9.1 is still valid for version 1.7+ -> 1.20.4"... I just added it as a separate topic on the spigot page.
