### ISSUE TITLE
Enabling of cemeteries?

### ISSUE THREAD

**Issue by manulopezw** [AvarionMC/graves#24]
I see that the addon includes cementeries, burialgrounds, graveyards, churchyards and necropolis
Is there any difference between them?

**Comment by svaningelgem** [comment]
From what I could glance from the code is that this part wasn't finished by ranull. I can only surmise that the graves would spawn in a designated area.

Feel free to go through the code and enable it? 😁

**Comment by svaningelgem** [comment]
Duplicate of #9
