### ISSUE TITLE
Problem with geysermc bedrock

### ISSUE THREAD

**Issue by sandipanop** [AvarionMC/graves#31]
Problem 
Unable to respawn after death bedrock geyserMC 
![IMG_0785](https://github.com/AvarionMC/graves/assets/174722496/b296b82d-6b90-402c-bda1-a9ace549a05a)

**Comment by svaningelgem** [comment]
Is it possible to put the stacktrace in a codeblock (\`\`\`...\`\`\`) & tell me what version you are using?

**Comment by sandipanop** [comment]
Yeah i find out that the problem occurs even without using this plugin,
I think its problem with my server

**Comment by sandipanop** [comment]
Yeah guys this is problem with my server
My hosting company pre installed a paper
That was the problem 
I download the new paper from official paper website 
And then its working fine
