### ISSUE TITLE
Graves dont work in the end

### ISSUE THREAD

**Issue by LepidusCraft** [AvarionMC/graves#32]
pretty simple graves just dont spawn in the end and make you keep inventory

**Comment by svaningelgem** [comment]
I'll need to look into that. Just saying: I read your message.

**Comment by svaningelgem** [comment]
Seems to work just fine?
![image](https://github.com/AvarionMC/graves/assets/199434/58e4c78c-efdc-44fd-a750-912c9bc726c5)
![image](https://github.com/AvarionMC/graves/assets/199434/f588a356-c3af-4367-b7b2-d20a019b8c8a)
