### ISSUE TITLE
Do you plan to put it in Aternos?

### ISSUE THREAD

**Issue by Yisusle** [AvarionMC/graves#55]
### Checks

- [X] I am running the [latest version](https://www.spigotmc.org/resources/graves.116202/history) of this plugin.
- [X] There isn't another issue about this.

### Requested Feature

Plugin in Aternos

### Why is this needed?

It would be good if it were there since the plugin that is in Aternos is no longer updated.

👍

**Comment by svaningelgem** [comment]
The plugin is on [SpigotMC](https://www.spigotmc.org/resources/graves.116202/history).
If you want to have this on this hosting company, I'd suggest to contact their support instead.
